# Generated by Django 3.0.1 on 2020-01-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
