# Generated by Django 3.0.1 on 2020-01-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0002_auto_20200111_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altura_rompiente',
            options={'verbose_name': 'Altura rompiente', 'verbose_name_plural': 'Alturas rompientes'},
        ),
        migrations.AlterModelOptions(
            name='cantones',
            options={'verbose_name': 'Cantón', 'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='fase_lunar',
            options={'verbose_name': 'Fase lunar', 'verbose_name_plural': 'Fases lunares'},
        ),
        migrations.AlterModelOptions(
            name='parroquias',
            options={'verbose_name': 'Parróquia', 'verbose_name_plural': 'Parróquias'},
        ),
        migrations.AlterModelOptions(
            name='periodos',
            options={'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipo_oleaje',
            options={'verbose_name': 'Tipo de oleaje', 'verbose_name_plural': 'Tipos de oleajes'},
        ),
    ]
